/* Business features — what a business buys, and the modules that provide it.
 *
 * This is the vocabulary a business speaks: "quote negotiation", "faceted search", "buy online, pick
 * up in store". Every feature names the modules that must be installed for it to exist, which makes
 * three things computable that were previously opinions:
 *
 *   • whether a PBC has a feature       — are all its modules in that package?
 *   • what a package is missing         — which modules would you add to get it?
 *   • what a custom package can do      — the same question, live, in the builder.
 *
 * AUTHORED, not generated: the module list under each feature is a judgement about what the feature
 * genuinely requires, and no parser can make it. But it is CHECKED — check-content.js fails if a
 * feature names a module that is not in the active registry, so the catalogue cannot rot quietly.
 *
 * `modules` holds two kinds of entry:
 *
 *   'VirtoCommerce.Catalog'                       — required outright.
 *   ['VirtoCommerce.ElasticSearch8', '…Algolia']  — an any-of slot: one of these satisfies it.
 *
 * The any-of slot matters more than it looks. Search engines, payment gateways, identity providers,
 * CMS connectors and telemetry backends are interchangeable by design, and a package that ships
 * Algolia instead of Elasticsearch has the feature just as much. Without any-of, every such package
 * would read as missing capabilities it plainly has.
 *
 * Rules for adding one:
 *   1. Name it as a business would say it, not as the code does. "Wish lists", not "ProductWishlist".
 *   2. `modules` is the minimum set. If the feature works without a module, leave that module out —
 *      an over-stated requirement makes a package look less capable than it is.
 *   3. The blurb says what the business gets in one sentence. No module names inside it.
 *   4. Prefer a feature a stakeholder would recognise from their own requirements document.
 *   5. Interchangeable providers belong in one any-of slot, most commonly deployed first — the first
 *      entry is what the page suggests adding when the slot is empty.
 */
window.VC_MAP_FEATURES = [

  /* ---------- Catalog & discovery ---------- */
  { id: 'product-catalog', name: 'Product catalogue', category: 'Catalog & discovery',
    blurb: 'Hold products, variations and categories with the attributes that describe them.',
    modules: ['VirtoCommerce.Catalog'] },
  { id: 'faceted-search', name: 'Faceted search & filters', category: 'Catalog & discovery',
    blurb: 'Shoppers narrow a large assortment by the properties that matter to them.',
    modules: ['VirtoCommerce.Catalog', 'VirtoCommerce.Search'] },
  { id: 'catalog-api', name: 'Catalogue over API', category: 'Catalog & discovery',
    blurb: 'Any channel — web, app, marketplace, AI agent — reads the catalogue through one GraphQL endpoint.',
    modules: ['VirtoCommerce.XCatalog', 'VirtoCommerce.Xapi'] },
  { id: 'personalised-catalog', name: 'Personalised assortment', category: 'Catalog & discovery',
    blurb: 'Different audiences see different products, without maintaining a second catalogue.',
    modules: ['VirtoCommerce.CatalogPersonalization'] },
  { id: 'recommendations', name: 'Product recommendations', category: 'Catalog & discovery',
    blurb: '"Customers also bought" and similar lists on product and basket pages.',
    modules: ['VirtoCommerce.XRecommend'] },
  { id: 'related-products', name: 'Related products by rule', category: 'Catalog & discovery',
    blurb: 'Accessories, alternatives and cross-sells generated from rules instead of linked by hand.',
    modules: ['VirtoCommerce.DynamicAssociationsModule'] },
  { id: 'product-reviews', name: 'Ratings & reviews', category: 'Catalog & discovery',
    blurb: 'Shoppers rate and review products, with moderation before anything appears.',
    modules: ['VirtoCommerce.CustomerReviews'] },
  { id: 'back-in-stock', name: 'Back-in-stock alerts', category: 'Catalog & discovery',
    blurb: 'Shoppers ask to be told when a sold-out product returns, and the demand is recorded.',
    modules: ['VirtoCommerce.BackInStock'] },
  { id: 'seo-urls', name: 'SEO-friendly URLs & redirects', category: 'Catalog & discovery',
    blurb: 'Readable addresses for every product and page, and redirects when something moves.',
    modules: ['VirtoCommerce.Seo'] },
  { id: 'sitemap', name: 'Sitemaps for search engines', category: 'Catalog & discovery',
    blurb: 'Search engines discover the whole catalogue instead of crawling their way in.',
    modules: ['VirtoCommerce.Sitemaps'] },

  /* ---------- Product data (PIM) ---------- */
  { id: 'product-authoring', name: 'Product data authoring', category: 'Product data',
    blurb: 'Category managers create and edit product data in one place instead of in spreadsheets.',
    modules: ['VirtoCommerce.Catalog'] },
  { id: 'bulk-product-import', name: 'Bulk product import & export', category: 'Product data',
    blurb: 'Load or extract thousands of products as files, with the mapping saved for next time.',
    modules: ['VirtoCommerce.CatalogCsvImportModule'] },
  { id: 'bulk-edit', name: 'Bulk editing', category: 'Product data',
    blurb: 'Recategorise or re-tag hundreds of records in one action rather than one at a time.',
    modules: ['VirtoCommerce.BulkActionsModule'] },
  { id: 'data-completeness', name: 'Data completeness scoring', category: 'Product data',
    blurb: 'See which products are not ready to publish, per channel, before a customer finds the gap.',
    modules: ['VirtoCommerce.CatalogPublishing'] },
  { id: 'product-media', name: 'Images, video & documents', category: 'Product data',
    blurb: 'Rich media on products, stored wherever the deployment keeps files.',
    modules: ['VirtoCommerce.Assets', 'VirtoCommerce.Catalog'] },
  { id: 'image-variants', name: 'Automatic image sizes', category: 'Product data',
    blurb: 'One upload becomes every size the storefront needs.',
    modules: ['VirtoCommerce.ImageTools'] },
  { id: 'product-snapshot', name: 'Product history snapshots', category: 'Product data',
    blurb: 'Keep proof of what a product looked like when someone ordered it.',
    modules: ['VirtoCommerce.ProductSnapshot'] },
  { id: 'measurements', name: 'Units & measurements', category: 'Product data',
    blurb: 'Sell by weight, length or volume with units the business actually uses.',
    modules: ['VirtoCommerce.Core', 'VirtoCommerce.Catalog'] },

  /* ---------- Pricing ---------- */
  { id: 'price-lists', name: 'Price lists & assignments', category: 'Pricing',
    blurb: 'Different prices for different audiences, decided per request rather than stored per product.',
    modules: ['VirtoCommerce.Pricing'] },
  { id: 'bulk-price-import', name: 'Bulk price import', category: 'Pricing',
    blurb: 'Replace a whole price list from a supplier file.',
    modules: ['VirtoCommerce.PriceExportImport'] },
  { id: 'contract-pricing', name: 'Contracted prices', category: 'Pricing',
    blurb: 'Negotiated rates for a customer or organisation, valid for an agreed period.',
    modules: ['VirtoCommerce.Contracts'] },
  { id: 'multi-currency', name: 'Multiple currencies', category: 'Pricing',
    blurb: 'Sell in the currencies each market expects, with rates you control.',
    modules: ['VirtoCommerce.Core', 'VirtoCommerce.Store'] },
  { id: 'tax-calculation', name: 'Tax calculation', category: 'Pricing',
    blurb: 'Tax worked out per order rather than typed in, by whichever provider you choose.',
    modules: ['VirtoCommerce.Tax'] },
  { id: 'tax-service', name: 'Jurisdiction-grade tax', category: 'Pricing',
    blurb: 'Real rates, exemptions and filing data from a tax service.',
    modules: ['VirtoCommerce.AvalaraTax'] },

  /* ---------- Cart & checkout ---------- */
  { id: 'cart', name: 'Shopping cart', category: 'Cart & checkout',
    blurb: 'A basket that survives between visits and recalculates as it changes.',
    modules: ['VirtoCommerce.Cart'] },
  { id: 'cart-api', name: 'Cart & checkout over API', category: 'Cart & checkout',
    blurb: 'A storefront drives the whole basket and checkout flow in single round trips.',
    modules: ['VirtoCommerce.XCart', 'VirtoCommerce.Xapi'] },
  { id: 'wishlists', name: 'Wish lists', category: 'Cart & checkout',
    blurb: 'Shoppers save products for later, in one list or several.',
    modules: ['VirtoCommerce.Cart'] },
  { id: 'checkout-payment', name: 'Payment methods', category: 'Cart & checkout',
    blurb: 'Offer the ways to pay each store needs, configured rather than coded.',
    modules: ['VirtoCommerce.Payment'] },
  { id: 'card-payments', name: 'Card payments via gateway', category: 'Cart & checkout',
    blurb: 'Take card payments without card data entering your systems.',
    modules: ['VirtoCommerce.Payment', ['VirtoCommerce.AuthorizeNetPayment', 'VirtoCommerce.CyberSourcePayment', 'VirtoCommerce.Datatrans']] },
  { id: 'payment-vault', name: 'Card data kept in a vault', category: 'Cart & checkout',
    blurb: 'Sensitive payment details live outside the platform, which shrinks what has to be audited.',
    modules: ['VirtoCommerce.Skyflow'] },
  { id: 'invoice-payment', name: 'Pay by invoice or on account', category: 'Cart & checkout',
    blurb: 'B2B buyers order now and settle later, with no gateway involved.',
    modules: ['VirtoCommerce.NativePaymentMethods'] },
  { id: 'shipping-methods', name: 'Shipping methods & rates', category: 'Cart & checkout',
    blurb: 'Delivery options per store, priced by rule or by carrier.',
    modules: ['VirtoCommerce.Shipping'] },
  { id: 'carrier-rates', name: 'Live carrier rates & labels', category: 'Cart & checkout',
    blurb: 'Quote real shipping prices at checkout and print labels afterwards.',
    modules: ['VirtoCommerce.ShipStation'] },
  { id: 'bopis', name: 'Buy online, pick up in store', category: 'Cart & checkout',
    blurb: 'Shoppers choose a location to collect from, based on what is actually in stock there.',
    modules: ['VirtoCommerce.XPickup', 'VirtoCommerce.Shipping', 'VirtoCommerce.Inventory'] },
  { id: 'abandoned-cart', name: 'Abandoned-cart reminders', category: 'Cart & checkout',
    blurb: 'Shoppers who left something behind are reminded, on a schedule you set.',
    modules: ['VirtoCommerce.Cart', 'VirtoCommerce.Notifications'] },

  /* ---------- Orders & fulfilment ---------- */
  { id: 'order-management', name: 'Order management', category: 'Orders & fulfilment',
    blurb: 'The committed record of a sale, with everything that happens to it afterwards.',
    modules: ['VirtoCommerce.Orders'] },
  { id: 'order-workspace', name: 'Agent order workspace', category: 'Orders & fulfilment',
    blurb: 'A purpose-built screen for the people who work orders all day.',
    modules: ['VirtoCommerce.OrderManagement'] },
  { id: 'order-history-api', name: 'Order history for shoppers', category: 'Orders & fulfilment',
    blurb: 'Customers see and act on their own orders from the storefront.',
    modules: ['VirtoCommerce.XOrder'] },
  { id: 'inventory', name: 'Stock & fulfilment centres', category: 'Orders & fulfilment',
    blurb: 'Know what is available and where it sits, and stop selling what is gone.',
    modules: ['VirtoCommerce.Inventory'] },
  { id: 'returns', name: 'Returns & refunds', category: 'Orders & fulfilment',
    blurb: 'Handle goods coming back and money going out, as separate steps that can fail apart.',
    modules: ['VirtoCommerce.Return'] },
  { id: 'subscriptions', name: 'Subscriptions & recurring orders', category: 'Orders & fulfilment',
    blurb: 'Repeat orders placed on schedule, with pause, resume and cancel.',
    modules: ['VirtoCommerce.Subscription'] },
  { id: 'order-status-flow', name: 'Configurable status flows', category: 'Orders & fulfilment',
    blurb: 'The states an order or quote can move through, changed as the business changes.',
    modules: ['VirtoCommerce.StateMachine'] },
  { id: 'human-tasks', name: 'Approvals & assigned tasks', category: 'Orders & fulfilment',
    blurb: 'Human steps in a process get an owner, a due date and a record.',
    modules: ['VirtoCommerce.TaskManagement'] },

  /* ---------- B2B buying ---------- */
  { id: 'organisations', name: 'Companies & buyer accounts', category: 'B2B buying',
    blurb: 'Sell to organisations: their people, their structure, and who may order.',
    modules: ['VirtoCommerce.Customer'] },
  { id: 'self-service-accounts', name: 'Customer self-service', category: 'B2B buying',
    blurb: 'A customer administrator manages their own colleagues and addresses, within your limits.',
    modules: ['VirtoCommerce.ProfileExperienceApiModule'] },
  { id: 'quotes', name: 'Quote negotiation', category: 'B2B buying',
    blurb: 'A buyer asks for a price, a salesperson answers, and the agreed quote becomes an order.',
    modules: ['VirtoCommerce.Quote'] },
  { id: 'sales-rep', name: 'Ordering on behalf of a customer', category: 'B2B buying',
    blurb: 'A sales representative works inside the customer’s account and places the order for them.',
    modules: ['VirtoCommerce.SalesRep'] },
  { id: 'bulk-order', name: 'Fast reordering', category: 'B2B buying',
    blurb: 'Buyers rebuild a basket from a previous order or a saved list instead of searching again.',
    modules: ['VirtoCommerce.Cart', 'VirtoCommerce.Orders'] },

  /* ---------- Customer & accounts ---------- */
  { id: 'customer-data', name: 'Customer records', category: 'Customer & accounts',
    blurb: 'Contacts, addresses, notes and preferences behind every order.',
    modules: ['VirtoCommerce.Customer'] },
  { id: 'customer-import', name: 'Customer import & export', category: 'Customer & accounts',
    blurb: 'Migrate contacts in, and pull lists out, as files.',
    modules: ['VirtoCommerce.CustomerExportImport'] },
  { id: 'sso', name: 'Single sign-on', category: 'Customer & accounts',
    blurb: 'People sign in with an identity your organisation already trusts.',
    modules: [['VirtoCommerce.AzureAD', 'VirtoCommerce.OpenIdConnectModule', 'VirtoCommerce.GoogleSSO']] },
  { id: 'sso-any-idp', name: 'A customer’s own identity provider', category: 'Customer & accounts',
    blurb: 'Each buying organisation authenticates against its own directory, whichever standard one it is.',
    modules: ['VirtoCommerce.OpenIdConnectModule'] },
  { id: 'gdpr', name: 'Data export & erasure requests', category: 'Customer & accounts',
    blurb: 'Answer a subject access or deletion request across everything the platform holds.',
    modules: ['VirtoCommerce.GDPR'] },

  /* ---------- Content & experience ---------- */
  { id: 'cms-pages', name: 'Pages, blocks & menus', category: 'Content & experience',
    blurb: 'Editorial content per store, changed by marketing without a release.',
    modules: ['VirtoCommerce.Content'] },
  { id: 'page-builder', name: 'Visual page building', category: 'Content & experience',
    blurb: 'Marketing composes layouts from blocks by dragging, with a live preview.',
    modules: ['VirtoCommerce.PageBuilderModule'] },
  { id: 'content-api', name: 'Content over API', category: 'Content & experience',
    blurb: 'A storefront fetches pages and menus from the same endpoint as its products.',
    modules: ['VirtoCommerce.XCMS'] },
  { id: 'news', name: 'News & articles', category: 'Content & experience',
    blurb: 'Announcements and editorial articles with their own dates and categories.',
    modules: ['VirtoCommerce.News'] },
  { id: 'multi-store', name: 'Multiple storefronts', category: 'Content & experience',
    blurb: 'Several stores, markets or brands from one installation, each configured its own way.',
    modules: ['VirtoCommerce.Store'] },
  { id: 'white-label', name: 'Per-brand branding', category: 'Content & experience',
    blurb: 'Each brand or customer portal gets its own identity from data, not a separate deployment.',
    modules: ['VirtoCommerce.WhiteLabeling'] },
  { id: 'external-cms', name: 'Content from an external CMS', category: 'Content & experience',
    blurb: 'Editors keep working in the CMS the business already owns.',
    modules: [['VirtoCommerce.Contentful', 'VirtoCommerce.Sanity', 'VirtoCommerce.BuilderIO']] },
  { id: 'simple-pages', name: 'Lightweight content pages', category: 'Content & experience',
    blurb: 'A few informational pages managed beside the catalogue, without a CMS to run.',
    modules: ['VirtoCommerce.Pages'] },
  { id: 'storefront-config', name: 'Storefront settings over API', category: 'Content & experience',
    blurb: 'A storefront configures itself — theme, locale, feature flags — from the same endpoint as its data.',
    modules: ['VirtoCommerce.XFrontend'] },
  { id: 'storefront-uploads', name: 'File uploads from the storefront', category: 'Content & experience',
    blurb: 'Customers attach documents to orders and quotes, and get them back later.',
    modules: ['VirtoCommerce.FileExperienceApi'] },
  { id: 'localisation', name: 'Multi-language storefronts', category: 'Content & experience',
    blurb: 'Sell in each market’s language, including the back office.',
    modules: ['VirtoCommerce.Store', 'VirtoCommerce.Content'] },

  /* ---------- Marketing & loyalty ---------- */
  { id: 'promotions', name: 'Promotions & discounts', category: 'Marketing & loyalty',
    blurb: 'Campaign rules that change what a shopper pays, configured rather than coded.',
    modules: ['VirtoCommerce.Marketing'] },
  { id: 'coupons', name: 'Coupons with usage limits', category: 'Marketing & loyalty',
    blurb: 'Codes that can be limited per customer and reported on afterwards.',
    modules: ['VirtoCommerce.Marketing'] },
  { id: 'dynamic-content', name: 'Targeted on-site content', category: 'Marketing & loyalty',
    blurb: 'Banners and blocks that change by audience, place or campaign.',
    modules: ['VirtoCommerce.MarketingExperienceApi', 'VirtoCommerce.Marketing'] },
  { id: 'loyalty', name: 'Loyalty points & tiers', category: 'Marketing & loyalty',
    blurb: 'Customers earn and spend rewards, with balances the storefront can show.',
    modules: ['VirtoCommerce.Loyalty'] },
  { id: 'transactional-email', name: 'Transactional email & SMS', category: 'Marketing & loyalty',
    blurb: 'Order confirmations and alerts, with wording editable and delivery on record.',
    modules: ['VirtoCommerce.Notifications'] },
  { id: 'web-analytics', name: 'Funnel & revenue analytics', category: 'Marketing & loyalty',
    blurb: 'Marketing measures the funnel in the analytics tool it already uses.',
    modules: ['VirtoCommerce.GoogleEcommerceAnalytics'] },
  { id: 'behaviour-insights', name: 'Session recordings & heatmaps', category: 'Marketing & loyalty',
    blurb: 'Watch how shoppers actually behave, instead of arguing about it.',
    modules: ['VirtoCommerce.Hotjar'] },

  /* ---------- Integration & operations ---------- */
  { id: 'webhooks', name: 'Outbound webhooks', category: 'Integration & operations',
    blurb: 'External systems are told when something happens, without polling your API.',
    modules: ['VirtoCommerce.WebHooks'] },
  { id: 'event-queue', name: 'Event streaming to a queue', category: 'Integration & operations',
    blurb: 'A durable stream of changes for integrations that must not miss one.',
    modules: ['VirtoCommerce.EventBus'] },
  { id: 'generic-export', name: 'Data export as files', category: 'Integration & operations',
    blurb: 'Any module’s data pulled out as CSV or JSON, on demand, from the back office.',
    modules: ['VirtoCommerce.Export'] },
  { id: 'file-import', name: 'File import with audit', category: 'Integration & operations',
    blurb: 'Reusable import profiles, with every run and rejection recorded.',
    modules: ['VirtoCommerce.Import'] },
  { id: 'background-jobs', name: 'Background processing', category: 'Integration & operations',
    blurb: 'Long or scheduled work runs outside the request, and survives a restart.',
    modules: ['VirtoCommerce.BackgroundJobs'] },
  { id: 'audit-trail', name: 'Audit trail', category: 'Integration & operations',
    blurb: 'A record of who changed what, kept for as long as compliance requires.',
    modules: ['VirtoCommerce.AuditLog'] },
  { id: 'backup-restore', name: 'Backup & restore', category: 'Integration & operations',
    blurb: 'Move data between environments, and rehearse recovery rather than assume it.',
    modules: ['VirtoCommerce.BackupRestore'] },
  { id: 'monitoring', name: 'Operational monitoring', category: 'Integration & operations',
    blurb: 'See what a running instance is doing, and why it stopped.',
    modules: [['VirtoCommerce.ApplicationInsights', 'VirtoCommerce.OpenTelemetry', 'VirtoCommerce.SeqLog']] },
  { id: 'search-engine-choice', name: 'Search engine of your choice', category: 'Integration & operations',
    blurb: 'Run search on the engine your infrastructure already provides, hosted or managed.',
    modules: ['VirtoCommerce.Search', ['VirtoCommerce.ElasticSearch8', 'VirtoCommerce.ElasticSearch9', 'VirtoCommerce.AzureSearch', 'VirtoCommerce.AlgoliaSearch', 'VirtoCommerce.OpenSearch', 'VirtoCommerce.ElasticAppSearch', 'VirtoCommerce.LuceneSearch']] },
  { id: 'cloud-storage', name: 'File storage backend', category: 'Integration & operations',
    blurb: 'Decide where uploaded files live — a local disk, or cloud storage behind a CDN.',
    modules: ['VirtoCommerce.Assets', ['VirtoCommerce.AzureBlobAssets', 'VirtoCommerce.FileSystemAssets']] },
  { id: 'central-config', name: 'Central configuration & feature flags', category: 'Integration & operations',
    blurb: 'Change settings and switch features on across every instance without a redeploy.',
    modules: ['VirtoCommerce.AzureAppConfiguration'] },
  { id: 'env-compare', name: 'Environment comparison', category: 'Integration & operations',
    blurb: 'See exactly how staging differs from production before a release goes wrong.',
    modules: ['VirtoCommerce.EnvironmentsCompare'] },
  { id: 'maintenance-ops', name: 'Scheduled maintenance operations', category: 'Integration & operations',
    blurb: 'Routine housekeeping runs on a schedule instead of on someone’s memory.',
    modules: ['VirtoCommerce.SystemOperations'] },
  { id: 'admin-extensions', name: 'Extendable back office', category: 'Integration & operations',
    blurb: 'Teams add their own back-office screens without rebuilding the application.',
    modules: ['VirtoCommerce.ModuleFederation'] },
  { id: 'adhoc-reporting', name: 'Ad-hoc reporting', category: 'Integration & operations',
    blurb: 'Answer a data question today, without a BI project.',
    modules: ['VirtoCommerce.SqlQueries'] },

  /* ---------- AI & agents ---------- */
  { id: 'ai-foundation', name: 'AI provider foundation', category: 'AI & agents',
    blurb: 'A configured model provider that features can use, with access permissioned.',
    modules: ['VirtoCommerce.AI'] },
  { id: 'agent-commerce', name: 'Agent & marketplace protocol', category: 'AI & agents',
    blurb: 'External agents and marketplaces browse and buy through a standard protocol, including MCP.',
    modules: ['VirtoCommerce.UCP'] },
  { id: 'push-messages', name: 'In-app alerts for staff', category: 'AI & agents',
    blurb: 'People working in the back office are told when their long job finishes.',
    modules: ['VirtoCommerce.PushMessages'] }
];
