/* GENERATED by tools/build-active-modules.js from vc-modules/modules_v3.json — do not edit.
 * 96 modules whose newest published version is >= 3.1000.0.
 * Identity, version, platform floor and dependencies (with the optional flag) all come from the
 * registry, so this file is a projection of it and never a second opinion. `name` is the registry
 * title with package-list noise stripped; `registryTitle` is that title verbatim.
 */
window.VC_ACTIVE_MODULES = [
 {
  "id": "VirtoCommerce.AI",
  "moleculeId": "VirtoCommerce.AI",
  "slug": "mod-ai",
  "name": "AI",
  "registryTitle": "VirtoCommerce AI",
  "description": "AI manifest aggregation module for VirtoCommerce Platform. Collects and exposes AI tool and agent definitions from all installed modules.",
  "version": "3.1001.0",
  "versionTag": "alpha.28",
  "platformVersion": "3.1002.0",
  "groups": [],
  "tags": "extension module",
  "repo": "vc-module-ai",
  "repoUrl": "https://github.com/VirtoCommerce/vc-module-ai",
  "dependsOn": [],
  "optional": [],
  "incompatibleWith": []
 },
 {
  "id": "VirtoCommerce.AlgoliaSearch",
  "moleculeId": "VirtoCommerce.AlgoliaSearch",
  "slug": "mod-algolia-search",
  "name": "Algolia Search",
  "registryTitle": "Algolia Search",
  "description": "Indexed search functionality with Algolia Search Engine",
  "version": "3.1002.0",
  "versionTag": "alpha.77",
  "platformVersion": "3.1002.0",
  "groups": [],
  "tags": "algolia search",
  "repo": "vc-module-algolia-search",
  "repoUrl": "https://github.com/VirtoCommerce/vc-module-algolia-search",
  "dependsOn": [
   "Search"
  ],
  "optional": [],
  "incompatibleWith": []
 },
 {
  "id": "VirtoCommerce.Assets",
  "moleculeId": "VirtoCommerce.Assets",
  "slug": "mod-assets",
  "name": "Assets Management",
  "registryTitle": "Assets Management",
  "description": "Common abstractions for asset search, retrieval, and manipulation, making it easy for developers to work with assets regardless of their underlying storage location.",
  "version": "3.1006.0",
  "versionTag": "alpha.202",
  "platformVersion": "3.1039.0",
  "groups": [
   "commerce"
  ],
  "tags": "assets",
  "repo": "vc-module-assets",
  "repoUrl": "https://github.com/VirtoCommerce/vc-module-assets",
  "dependsOn": [],
  "optional": [],
  "incompatibleWith": []
 },
 {
  "id": "VirtoCommerce.AuditLog",
  "moleculeId": "VirtoCommerce.AuditLog",
  "slug": "mod-audit-log",
  "name": "Audit Log",
  "registryTitle": "Audit Log",
  "description": "Provides extended audit features",
  "version": "3.1003.0",
  "versionTag": "alpha.61",
  "platformVersion": "3.1007.10",
  "groups": [],
  "tags": "extension module",
  "repo": "vc-module-audit-log",
  "repoUrl": "https://github.com/VirtoCommerce/vc-module-audit-log",
  "dependsOn": [
   "ApplicationInsights"
  ],
  "optional": [],
  "incompatibleWith": []
 },
 {
  "id": "VirtoCommerce.AuthorizeNetPayment",
  "moleculeId": "VirtoCommerce.AuthorizeNetPayment",
  "slug": "mod-authorize-net-payment",
  "name": "Authorize.Net Payment Method",
  "registryTitle": "Authorize.Net Payment Method",
  "description": "Provides the integration with Authorize.Net payment provider",
  "version": "3.1004.0",
  "versionTag": "alpha.118",
  "platformVersion": "3.1039.0",
  "groups": [
   "commerce"
  ],
  "tags": "extension module",
  "repo": "vc-module-authorize-net",
  "repoUrl": "https://github.com/VirtoCommerce/vc-module-authorize-net",
  "dependsOn": [
   "Orders",
   "Payment"
  ],
  "optional": [],
  "incompatibleWith": []
 },
 {
  "id": "VirtoCommerce.AvalaraTax",
  "moleculeId": "VirtoCommerce.AvalaraTax",
  "slug": "mod-avalara-tax",
  "name": "Avalara Tax Provider",
  "registryTitle": "Avalara Tax Provider",
  "description": "Provides real time integration with Avalara Tax https://www.avalara.com/",
  "version": "3.1004.0",
  "versionTag": "alpha.357",
  "platformVersion": "3.1039.0",
  "groups": [],
  "tags": "avalara tax",
  "repo": "vc-module-avatax",
  "repoUrl": "https://github.com/VirtoCommerce/vc-module-avatax",
  "dependsOn": [
   "Inventory",
   "Orders",
   "Search",
   "Shipping",
   "Store",
   "Tax"
  ],
  "optional": [],
  "incompatibleWith": []
 },
 {
  "id": "VirtoCommerce.AzureAD",
  "moleculeId": "VirtoCommerce.AzureAD",
  "slug": "mod-azure-ad",
  "name": "Azure Active Directory Single Sign-On",
  "registryTitle": "Azure Active Directory Single Sign-On",
  "description": "Azure AD SSO integrates with Azure AD to provide secure authentication and authorization for cloud and on-premises applications.",
  "version": "3.1003.0",
  "versionTag": "alpha.77",
  "platformVersion": "3.1039.0",
  "groups": [
   "commerce"
  ],
  "tags": "extension module",
  "repo": "vc-module-azure-ad",
  "repoUrl": "https://github.com/VirtoCommerce/vc-module-azure-ad",
  "dependsOn": [],
  "optional": [],
  "incompatibleWith": []
 },
 {
  "id": "VirtoCommerce.AzureAppConfiguration",
  "moleculeId": "VirtoCommerce.AzureAppConfiguration",
  "slug": "mod-azure-app-configuration",
  "name": "Azure App Configuration",
  "registryTitle": "Azure App Configuration",
  "description": "Allows using Azure App Configuration to externalize storage and management of your app settings for Virto Commerce",
  "version": "3.1003.0",
  "versionTag": "alpha.18",
  "platformVersion": "3.1038.0",
  "groups": [],
  "tags": "extension module",
  "repo": "vc-module-azure-app-configuration",
  "repoUrl": "https://github.com/VirtoCommerce/vc-module-azure-app-configuration",
  "dependsOn": [],
  "optional": [],
  "incompatibleWith": []
 },
 {
  "id": "VirtoCommerce.ApplicationInsights",
  "moleculeId": "VirtoCommerce.ApplicationInsights",
  "slug": "mod-application-insights",
  "name": "Azure Application Insights",
  "registryTitle": "Azure Application Insights",
  "description": "Enables developers and administrators to collect, monitor, and analyze application performance, usage, and diagnostic data",
  "version": "3.1005.0",
  "versionTag": "alpha.67",
  "platformVersion": "3.1039.0",
  "groups": [
   "commerce"
  ],
  "tags": "extension module",
  "repo": "vc-module-app-insights",
  "repoUrl": "https://github.com/VirtoCommerce/vc-module-app-insights",
  "dependsOn": [],
  "optional": [],
  "incompatibleWith": []
 },
 {
  "id": "VirtoCommerce.AzureBlobAssets",
  "moleculeId": "VirtoCommerce.AzureBlobAssets",
  "slug": "mod-azure-blob-assets",
  "name": "Azure Blob Storage Assets Provider",
  "registryTitle": "Azure Blob Storage Assets Provider",
  "description": "Provide integration with Azure Blob Storage for Assets Management",
  "version": "3.1007.0",
  "versionTag": "alpha.182",
  "platformVersion": "3.1039.0",
  "groups": [
   "commerce"
  ],
  "tags": "assets",
  "repo": "vc-module-azureblob-assets",
  "repoUrl": "https://github.com/VirtoCommerce/vc-module-azureblob-assets",
  "dependsOn": [
   "Assets"
  ],
  "optional": [],
  "incompatibleWith": []
 },
 {
  "id": "VirtoCommerce.AzureSearch",
  "moleculeId": "VirtoCommerce.AzureSearch",
  "slug": "mod-azure-search",
  "name": "Azure Search",
  "registryTitle": "Azure Search",
  "description": "Search functionality with Elastic Azure Search service",
  "version": "3.1007.0",
  "versionTag": "alpha.297",
  "platformVersion": "3.1039.0",
  "groups": [
   "commerce"
  ],
  "tags": "azure search",
  "repo": "vc-module-azure-search",
  "repoUrl": "https://github.com/VirtoCommerce/vc-module-azure-search",
  "dependsOn": [
   "Search"
  ],
  "optional": [],
  "incompatibleWith": []
 },
 {
  "id": "VirtoCommerce.BackInStock",
  "moleculeId": "VirtoCommerce.BackInStock",
  "slug": "mod-back-in-stock",
  "name": "Back In Stock",
  "registryTitle": "Back In Stock",
  "description": "Provides customer ability to subscribe for notification, when product is back in stock.",
  "version": "3.1002.0",
  "versionTag": "alpha.62",
  "platformVersion": "3.1007.10",
  "groups": [],
  "tags": "extension module",
  "repo": "vc-module-back-in-stock",
  "repoUrl": "https://github.com/VirtoCommerce/vc-module-back-in-stock",
  "dependsOn": [
   "Catalog",
   "Customer",
   "Inventory",
   "Notifications",
   "Store",
   "XCatalog",
   "Xapi"
  ],
  "optional": [],
  "incompatibleWith": []
 },
 {
  "id": "VirtoCommerce.BackgroundJobs",
  "moleculeId": "VirtoCommerce.BackgroundJobs",
  "slug": "mod-background-jobs",
  "name": "Background Jobs",
  "registryTitle": "Background Jobs",
  "description": "Handles asynchronous processing, allowing applications to offload time-consuming, repetitive, or resource-heavy tasks outside the platform",
  "version": "3.1050.0",
  "versionTag": "alpha.7",
  "platformVersion": "3.1050.0",
  "groups": [
   "commerce"
  ],
  "tags": "extension module",
  "repo": "vc-module-background-jobs",
  "repoUrl": "https://github.com/VirtoCommerce/vc-module-background-jobs",
  "dependsOn": [],
  "optional": [],
  "incompatibleWith": []
 },
 {
  "id": "VirtoCommerce.BackupRestore",
  "moleculeId": "VirtoCommerce.BackupRestore",
  "slug": "mod-backup-restore",
  "name": "Backup & Restore",
  "registryTitle": "Backup & Restore",
  "description": "The Backup & Restore module provides full platform backup and restore (export/import) for Virto Commerce. It packages platform data (users, roles, permissions, settings and dynamic properties) together with the data of all installed modules into a single, optionally AES-256 encrypted ZIP archive, and restores it on demand with real-time progress tracking and sample data installation.",
  "version": "3.1003.0",
  "versionTag": "alpha.13",
  "platformVersion": "3.1039.0",
  "groups": [
   "commerce"
  ],
  "tags": "extension module",
  "repo": "vc-module-backup-restore",
  "repoUrl": "https://github.com/VirtoCommerce/vc-module-backup-restore",
  "dependsOn": [
   "Assets"
  ],
  "optional": [],
  "incompatibleWith": []
 },
 {
  "id": "VirtoCommerce.BuilderIO",
  "moleculeId": "VirtoCommerce.BuilderIO",
  "slug": "mod-builder-io",
  "name": "Builder.io",
  "registryTitle": "Builder.io",
  "description": "Integration module for Builder.io",
  "version": "3.1005.0",
  "versionTag": "alpha.140",
  "platformVersion": "3.1002.0",
  "groups": [],
  "tags": "extension module",
  "repo": "vc-module-builder-io",
  "repoUrl": "https://github.com/VirtoCommerce/vc-module-builder-io",
  "dependsOn": [
   "Core",
   "Store"
  ],
  "optional": [
   "Pages"
  ],
  "incompatibleWith": []
 },
 {
  "id": "VirtoCommerce.BulkActionsModule",
  "moleculeId": "VirtoCommerce.BulkActionsModule",
  "slug": "mod-bulk-actions",
  "name": "Bulk Actions",
  "registryTitle": "Bulk Actions",
  "description": "Bulk actions module",
  "version": "3.1003.0",
  "versionTag": "alpha.254",
  "platformVersion": "3.1039.0",
  "groups": [
   "commerce"
  ],
  "tags": "extension module",
  "repo": "vc-module-bulk-actions",
  "repoUrl": "https://github.com/VirtoCommerce/vc-module-bulk-actions",
  "dependsOn": [
   "Core"
  ],
  "optional": [],
  "incompatibleWith": []
 },
 {
  "id": "VirtoCommerce.XPickup",
  "moleculeId": "VirtoCommerce.XPickup",
  "slug": "mod-xpickup",
  "name": "Buy online pickup in store (BOPIS) Experience API",
  "registryTitle": "Buy online pickup in store (BOPIS) Experience API",
  "description": "Handles buy online pickup in store (BOPIS) operations",
  "version": "3.1004.0",
  "versionTag": "alpha.51",
  "platformVersion": "3.1002.0",
  "groups": [],
  "tags": "extension module",
  "repo": "vc-module-x-pickup",
  "repoUrl": "https://github.com/VirtoCommerce/vc-module-x-pickup",
  "dependsOn": [
   "Cart",
   "Catalog",
   "Inventory",
   "Shipping",
   "Xapi"
  ],
  "optional": [],
  "incompatibleWith": []
 },
 {
  "id": "VirtoCommerce.XCart",
  "moleculeId": "VirtoCommerce.XCart",
  "slug": "mod-xcart",
  "name": "Cart Experience API",
  "registryTitle": "Cart Experience API",
  "description": "Dedicated to cart-related functionalities, ensuring efficient handling of shopping cart and checkout operations.",
  "version": "3.1029.0",
  "versionTag": "alpha.266",
  "platformVersion": "3.1048.0",
  "groups": [
   "commerce"
  ],
  "tags": "extension module",
  "repo": "vc-module-x-cart",
  "repoUrl": "https://github.com/VirtoCommerce/vc-module-x-cart",
  "dependsOn": [
   "Cart",
   "Catalog",
   "FileExperienceApi",
   "Inventory",
   "Marketing",
   "Payment",
   "Pricing",
   "Shipping",
   "XCatalog",
   "Xapi"
  ],
  "optional": [],
  "incompatibleWith": []
 },
 {
  "id": "VirtoCommerce.Catalog",
  "moleculeId": "VirtoCommerce.Catalog",
  "slug": "mod-catalog",
  "name": "Catalog",
  "registryTitle": "Catalog",
  "description": "Easily manage your products, categories, variations, and properties",
  "version": "3.1040.0",
  "versionTag": "alpha.2554",
  "platformVersion": "3.1039.0",
  "groups": [
   "commerce"
  ],
  "tags": "catalog",
  "repo": "vc-module-catalog",
  "repoUrl": "https://github.com/VirtoCommerce/vc-module-catalog",
  "dependsOn": [
   "Assets",
   "Core",
   "Search",
   "Seo",
   "Store"
  ],
  "optional": [
   "BulkActionsModule",
   "Export"
  ],
  "incompatibleWith": []
 },
 {
  "id": "VirtoCommerce.XCatalog",
  "moleculeId": "VirtoCommerce.XCatalog",
  "slug": "mod-xcatalog",
  "name": "Catalog Experience API",
  "registryTitle": "Catalog Experience API",
  "description": "Manages all catalog-related operations, from product listings to detailed item information.",
  "version": "3.1016.0",
  "versionTag": "alpha.217",
  "platformVersion": "3.1057.0",
  "groups": [
   "commerce"
  ],
  "tags": "extension module",
  "repo": "vc-module-x-catalog",
  "repoUrl": "https://github.com/VirtoCommerce/vc-module-x-catalog",
  "dependsOn": [
   "Catalog",
   "Xapi"
  ],
  "optional": [
   "Inventory",
   "Marketing",
   "Pricing"
  ],
  "incompatibleWith": []
 },
 {
  "id": "VirtoCommerce.CatalogPersonalization",
  "moleculeId": "VirtoCommerce.CatalogPersonalization",
  "slug": "mod-catalog-personalization",
  "name": "Catalog Personalization",
  "registryTitle": "Catalog Personalization",
  "description": "Help businesses personalize their categories and products to specific User Groups",
  "version": "3.1004.0",
  "versionTag": "alpha.304",
  "platformVersion": "3.1039.0",
  "groups": [
   "commerce"
  ],
  "tags": "catalog personalization products categories",
  "repo": "vc-module-catalog-personalization",
  "repoUrl": "https://github.com/VirtoCommerce/vc-module-catalog-personalization",
  "dependsOn": [
   "Catalog",
   "Core",
   "Search"
  ],
  "optional": [],
  "incompatibleWith": []
 },
 {
  "id": "VirtoCommerce.CatalogPublishing",
  "moleculeId": "VirtoCommerce.CatalogPublishing",
  "slug": "mod-catalog-publishing",
  "name": "Catalog Publishing",
  "registryTitle": "Catalog Publishing",
  "description": "Allow you to see progress on filling in information about products and marks missed info.",
  "version": "3.1006.0",
  "versionTag": "alpha.404",
  "platformVersion": "3.1039.0",
  "groups": [
   "commerce"
  ],
  "tags": "publishing filling",
  "repo": "vc-module-catalog-publishing",
  "repoUrl": "https://github.com/VirtoCommerce/vc-module-catalog-publishing",
  "dependsOn": [
   "Catalog",
   "Pricing"
  ],
  "optional": [],
  "incompatibleWith": []
 },
 {
  "id": "VirtoCommerce.XCMS",
  "moleculeId": "VirtoCommerce.XCMS",
  "slug": "mod-xcms",
  "name": "CMS Experience API",
  "registryTitle": "CMS Experience API",
  "description": "Integrates with content management systems, facilitating seamless content delivery and management.",
  "version": "3.1004.0",
  "versionTag": "alpha.78",
  "platformVersion": "3.1039.0",
  "groups": [
   "commerce"
  ],
  "tags": "extension module",
  "repo": "vc-module-x-cms",
  "repoUrl": "https://github.com/VirtoCommerce/vc-module-x-cms",
  "dependsOn": [
   "Content",
   "Customer",
   "Xapi"
  ],
  "optional": [
   "PageBuilderModule",
   "Pages"
  ],
  "incompatibleWith": []
 },
 {
  "id": "VirtoCommerce.PageBuilderModule",
  "moleculeId": "VirtoCommerce.PageBuilderModule",
  "slug": "mod-page-builder",
  "name": "CMS Page Builder",
  "registryTitle": "CMS Page Builder",
  "description": "Compose pages in visual page builder.",
  "version": "3.1022.0",
  "versionTag": "alpha.852",
  "platformVersion": "3.1039.0",
  "groups": [
   "commerce"
  ],
  "tags": "cms content pagebuilder",
  "repo": "vc-module-pagebuilder",
  "repoUrl": "https://github.com/VirtoCommerce/vc-module-pagebuilder",
  "dependsOn": [
   "Assets",
   "Content",
   "Core",
   "Customer",
   "Search",
   "Store"
  ],
  "optional": [
   "Pages"
  ],
  "incompatibleWith": []
 },
 {
  "id": "VirtoCommerce.Core",
  "moleculeId": "VirtoCommerce.Core",
  "slug": "mod-core",
  "name": "Commerce core",
  "registryTitle": "Commerce core module",
  "description": "Common e-commerce domain functionality",
  "version": "3.1008.0",
  "versionTag": "alpha.1709",
  "platformVersion": "3.1039.0",
  "groups": [
   "commerce"
  ],
  "tags": "security core",
  "repo": "vc-module-core",
  "repoUrl": "https://github.com/VirtoCommerce/vc-module-core",
  "dependsOn": [],
  "optional": [],
  "incompatibleWith": []
 },
 {
  "id": "VirtoCommerce.ProfileExperienceApiModule",
  "moleculeId": "VirtoCommerce.ProfileExperienceApiModule",
  "slug": "mod-profile-experience-api",
  "name": "Commerce Profile Experience API",
  "registryTitle": "Commerce Profile Experience API",
  "description": null,
  "version": "3.1016.0",
  "versionTag": "alpha.372",
  "platformVersion": "3.1039.0",
  "groups": [
   "commerce"
  ],
  "tags": "extension module",
  "repo": "vc-module-profile-experience-api",
  "repoUrl": "https://github.com/VirtoCommerce/vc-module-profile-experience-api",
  "dependsOn": [
   "Customer",
   "Notifications",
   "Xapi"
  ],
  "optional": [
   "Marketing",
   "Pricing",
   "Tax",
   "XOrder"
  ],
  "incompatibleWith": []
 },
 {
  "id": "VirtoCommerce.Customer",
  "moleculeId": "VirtoCommerce.Customer",
  "slug": "mod-customer",
  "name": "Companies and Contacts",
  "registryTitle": "Companies and Contacts",
  "description": "Managing customers contacts and organizations",
  "version": "3.1022.0",
  "versionTag": "alpha.1001",
  "platformVersion": "3.1052.0",
  "groups": [
   "commerce"
  ],
  "tags": "customer",
  "repo": "vc-module-customer",
  "repoUrl": "https://github.com/VirtoCommerce/vc-module-customer",
  "dependsOn": [
   "Core",
   "Notifications",
   "Search",
   "Seo",
   "Store"
  ],
  "optional": [],
  "incompatibleWith": []
 },
 {
  "id": "VirtoCommerce.Content",
  "moleculeId": "VirtoCommerce.Content",
  "slug": "mod-content",
  "name": "Content",
  "registryTitle": "Content",
  "description": "Easily create, edit, and publish content such as pages, blog posts, and news articles.",
  "version": "3.1004.0",
  "versionTag": "alpha.1056",
  "platformVersion": "3.1039.0",
  "groups": [
   "commerce"
  ],
  "tags": "cms menu",
  "repo": "vc-module-content",
  "repoUrl": "https://github.com/VirtoCommerce/vc-module-content",
  "dependsOn": [
   "Assets",
   "AzureBlobAssets",
   "FileSystemAssets",
   "Search",
   "Store"
  ],
  "optional": [],
  "incompatibleWith": []
 },
 {
  "id": "VirtoCommerce.Contentful",
  "moleculeId": "VirtoCommerce.Contentful",
  "slug": "mod-contentful",
  "name": "Contentful",
  "registryTitle": "Contentful",
  "description": "Integration for contentful.com.",
  "version": "3.1002.0",
  "versionTag": "alpha.130",
  "platformVersion": "3.1002.0",
  "groups": [],
  "tags": "",
  "repo": "vc-module-contentful",
  "repoUrl": "https://github.com/VirtoCommerce/vc-module-contentful",
  "repoUrlDerived": true,
  "dependsOn": [
   "Catalog",
   "Content",
   "Core",
   "Store"
  ],
  "optional": [
   "Pages"
  ],
  "incompatibleWith": []
 },
 {
  "id": "VirtoCommerce.Contracts",
  "moleculeId": "VirtoCommerce.Contracts",
  "slug": "mod-contracts",
  "name": "Contracts",
  "registryTitle": "Contracts",
  "description": "Contract based price personalization for customers and organizations",
  "version": "3.1004.0",
  "versionTag": "alpha.172",
  "platformVersion": "3.1039.0",
  "groups": [],
  "tags": "extension module",
  "repo": "vc-module-contract",
  "repoUrl": "https://github.com/VirtoCommerce/vc-module-contract",
  "dependsOn": [
   "Customer",
   "Pricing",
   "Store",
   "Xapi"
  ],
  "optional": [],
  "incompatibleWith": []
 },
 {
  "id": "VirtoCommerce.Xapi",
  "moleculeId": "VirtoCommerce.Xapi",
  "slug": "mod-xapi",
  "name": "Core Experience API",
  "registryTitle": "Core Experience API",
  "description": "Module represents a core functionality for GraphQL and other XAPI modules",
  "version": "3.1017.0",
  "versionTag": "alpha.192",
  "platformVersion": "3.1039.0",
  "groups": [
   "commerce"
  ],
  "tags": "extension module",
  "repo": "vc-module-x-api",
  "repoUrl": "https://github.com/VirtoCommerce/vc-module-x-api",
  "dependsOn": [
   "Customer",
   "Search",
   "Seo",
   "Store"
  ],
  "optional": [
   "ApplicationInsights",
   "Tax"
  ],
  "incompatibleWith": [
   "ExperienceApi"
  ]
 },
 {
  "id": "VirtoCommerce.CatalogCsvImportModule",
  "moleculeId": "VirtoCommerce.CatalogCsvImportModule",
  "slug": "mod-catalog-csv-import",
  "name": "CSV Catalog Export and Import",
  "registryTitle": "CSV Catalog Export and Import Module",
  "description": "Enables seamless export and import of catalog data in CSV format, simplifying data management and integration with external systems.",
  "version": "3.1003.0",
  "versionTag": "alpha.391",
  "platformVersion": "3.1039.0",
  "groups": [
   "commerce"
  ],
  "tags": "catalog csv export import",
  "repo": "vc-module-catalog-csv-export-import",
  "repoUrl": "https://github.com/VirtoCommerce/vc-module-catalog-csv-export-import",
  "dependsOn": [
   "Assets",
   "Catalog",
   "Core",
   "Inventory",
   "Pricing",
   "Store"
  ],
  "optional": [],
  "incompatibleWith": []
 },
 {
  "id": "VirtoCommerce.CustomerExportImport",
  "moleculeId": "VirtoCommerce.CustomerExportImport",
  "slug": "mod-customer-export-import",
  "name": "Customer Export Import",
  "registryTitle": "Customer Export Import",
  "description": "This module adds customers export and import functionality. Use it for customer management.",
  "version": "3.1003.0",
  "versionTag": "alpha.221",
  "platformVersion": "3.1039.0",
  "groups": [],
  "tags": "customer export import",
  "repo": "vc-module-customer-export-import",
  "repoUrl": "https://github.com/VirtoCommerce/vc-module-customer-export-import",
  "dependsOn": [
   "Assets",
   "Customer",
   "Store"
  ],
  "optional": [],
  "incompatibleWith": []
 },
 {
  "id": "VirtoCommerce.CyberSourcePayment",
  "moleculeId": "VirtoCommerce.CyberSourcePayment",
  "slug": "mod-cyber-source-payment",
  "name": "CyberSource Payment",
  "registryTitle": "CyberSource Payment Module",
  "description": "Integrates CyberSource's payment solutions into your Virto Commerce platform",
  "version": "3.1003.0",
  "versionTag": "alpha.75",
  "platformVersion": "3.1002.0",
  "groups": [],
  "tags": "extension module",
  "repo": "vc-module-cyber-source",
  "repoUrl": "https://github.com/VirtoCommerce/vc-module-cyber-source",
  "dependsOn": [
   "Core",
   "Customer",
   "Orders",
   "Payment"
  ],
  "optional": [],
  "incompatibleWith": []
 },
 {
  "id": "VirtoCommerce.Datatrans",
  "moleculeId": "VirtoCommerce.Datatrans",
  "slug": "mod-datatrans",
  "name": "Datatrans Payment",
  "registryTitle": "Datatrans Payment",
  "description": "Datatrans payment module provides integration with Datatrans payment gateway for Virto Commerce.",
  "version": "3.1003.0",
  "versionTag": "alpha.117",
  "platformVersion": "3.1002.0",
  "groups": [],
  "tags": "extension module",
  "repo": "vc-module-datatrans",
  "repoUrl": "https://github.com/VirtoCommerce/vc-module-datatrans",
  "dependsOn": [
   "Orders",
   "Payment",
   "Store"
  ],
  "optional": [],
  "incompatibleWith": []
 },
 {
  "id": "VirtoCommerce.DynamicAssociationsModule",
  "moleculeId": "VirtoCommerce.DynamicAssociationsModule",
  "slug": "mod-dynamic-associations",
  "name": "Dynamic Associations",
  "registryTitle": "Dynamic Associations",
  "description": "Dynamic rule based product associations module",
  "version": "3.1002.0",
  "versionTag": "pr-56-c27a",
  "platformVersion": "3.1039.0",
  "groups": [],
  "tags": "dynamicAssociations",
  "repo": "vc-module-dynamic-associations",
  "repoUrl": "https://github.com/VirtoCommerce/vc-module-dynamic-associations",
  "dependsOn": [
   "Catalog",
   "Core",
   "Marketing",
   "Store"
  ],
  "optional": [],
  "incompatibleWith": []
 },
 {
  "id": "VirtoCommerce.ElasticAppSearch",
  "moleculeId": "VirtoCommerce.ElasticAppSearch",
  "slug": "mod-elastic-app-search",
  "name": "Elastic App Search",
  "registryTitle": "Elastic App Search",
  "description": "Search functionality with Elastic App Search service",
  "version": "3.1002.0",
  "versionTag": "alpha.182",
  "platformVersion": "3.1002.0",
  "groups": [],
  "tags": "elastic app search",
  "repo": "vc-module-elastic-app-search",
  "repoUrl": "https://github.com/VirtoCommerce/vc-module-elastic-app-search",
  "dependsOn": [
   "Search"
  ],
  "optional": [],
  "incompatibleWith": []
 },
 {
  "id": "VirtoCommerce.ElasticSearch8",
  "moleculeId": "VirtoCommerce.ElasticSearch8",
  "slug": "mod-elastic-search8",
  "name": "Elastic Search 8",
  "registryTitle": "Elastic Search 8",
  "description": "Indexed search functionality with Elastic 8 engines",
  "version": "3.1008.0",
  "versionTag": "alpha.176",
  "platformVersion": "3.1039.0",
  "groups": [
   "commerce"
  ],
  "tags": "extension module",
  "repo": "vc-module-elastic-search-8",
  "repoUrl": "https://github.com/VirtoCommerce/vc-module-elastic-search-8",
  "dependsOn": [
   "Search"
  ],
  "optional": [],
  "incompatibleWith": []
 },
 {
  "id": "VirtoCommerce.ElasticSearch9",
  "moleculeId": "VirtoCommerce.ElasticSearch9",
  "slug": "mod-elastic-search9",
  "name": "Elastic Search 9",
  "registryTitle": "Elastic Search 9",
  "description": "Indexed search functionality with Elastic 9 engines.",
  "version": "3.1005.0",
  "versionTag": "alpha.49",
  "platformVersion": "3.1002.0",
  "groups": [],
  "tags": "extension module",
  "repo": "vc-module-elastic-search-9",
  "repoUrl": "https://github.com/VirtoCommerce/vc-module-elastic-search-9",
  "dependsOn": [
   "Search"
  ],
  "optional": [],
  "incompatibleWith": []
 },
 {
  "id": "VirtoCommerce.EnvironmentsCompare",
  "moleculeId": "VirtoCommerce.EnvironmentsCompare",
  "slug": "mod-environments-compare",
  "name": "Environments Compare",
  "registryTitle": "Environments Compare",
  "description": "Enables backend administrators to compare platform settings, environment configurations, and system information across multiple Virto Commerce environments",
  "version": "3.1002.0",
  "versionTag": "alpha.14",
  "platformVersion": "3.1007.10",
  "groups": [],
  "tags": "extension module",
  "repo": "vc-module-environments-compare",
  "repoUrl": "https://github.com/VirtoCommerce/vc-module-environments-compare",
  "dependsOn": [
   "Store"
  ],
  "optional": [],
  "incompatibleWith": []
 },
 {
  "id": "VirtoCommerce.EventBus",
  "moleculeId": "VirtoCommerce.EventBus",
  "slug": "mod-event-bus",
  "name": "Event Bus",
  "registryTitle": "Event Bus module",
  "description": "The module enables you to be notified of new messages or changes via a Message Queue of your choice",
  "version": "3.1010.0",
  "versionTag": "alpha.203",
  "platformVersion": "3.1007.10",
  "groups": [
   "commerce"
  ],
  "tags": "eventbus azureveventgrid",
  "repo": "vc-module-event-bus",
  "repoUrl": "https://github.com/VirtoCommerce/vc-module-event-bus",
  "dependsOn": [],
  "optional": [],
  "incompatibleWith": []
 },
 {
  "id": "VirtoCommerce.FileExperienceApi",
  "moleculeId": "VirtoCommerce.FileExperienceApi",
  "slug": "mod-file-experience-api",
  "name": "File Experience API",
  "registryTitle": "File Experience API",
  "description": "Manages all file-related operations, from file upload to file content download for different client applications.",
  "version": "3.1004.0",
  "versionTag": "alpha.89",
  "platformVersion": "3.1039.0",
  "groups": [
   "commerce"
  ],
  "tags": "extension module",
  "repo": "vc-module-file-experience-api",
  "repoUrl": "https://github.com/VirtoCommerce/vc-module-file-experience-api",
  "dependsOn": [
   "Assets",
   "Xapi"
  ],
  "optional": [],
  "incompatibleWith": []
 },
 {
  "id": "VirtoCommerce.FileSystemAssets",
  "moleculeId": "VirtoCommerce.FileSystemAssets",
  "slug": "mod-file-system-assets",
  "name": "File Systems Assets Provider",
  "registryTitle": "File Systems Assets Provider",
  "description": "Provide integration with File Systems for Assets Management",
  "version": "3.1004.0",
  "versionTag": "alpha.144",
  "platformVersion": "3.1039.0",
  "groups": [
   "commerce"
  ],
  "tags": "assets",
  "repo": "vc-module-filesystem-assets",
  "repoUrl": "https://github.com/VirtoCommerce/vc-module-filesystem-assets",
  "dependsOn": [
   "Assets"
  ],
  "optional": [],
  "incompatibleWith": []
 },
 {
  "id": "VirtoCommerce.XFrontend",
  "moleculeId": "VirtoCommerce.XFrontend",
  "slug": "mod-xfrontend",
  "name": "Frontend Experience API",
  "registryTitle": "Frontend Experience API",
  "description": "Built on top of the Virto Commerce XAPI platform, the Frontend Experience API exposes optimized queries specifically for rendering and user experience scenarios.",
  "version": "3.1006.0",
  "versionTag": "alpha.50",
  "platformVersion": "3.1039.0",
  "groups": [
   "commerce"
  ],
  "tags": "extension module",
  "repo": "vc-module-x-frontend",
  "repoUrl": "https://github.com/VirtoCommerce/vc-module-x-frontend",
  "dependsOn": [
   "ProfileExperienceApiModule",
   "Xapi"
  ],
  "optional": [
   "WhiteLabeling"
  ],
  "incompatibleWith": []
 },
 {
  "id": "VirtoCommerce.ModuleFederation",
  "moleculeId": "VirtoCommerce.ModuleFederation",
  "slug": "mod-module-federation",
  "name": "Frontend Modules Registry",
  "registryTitle": "Frontend Modules Registry",
  "description": "Provides API endpoint for dynamic frontend module discovery via Module Federation. Replaces static apps.json.",
  "version": "3.1000.0",
  "versionTag": null,
  "platformVersion": "3.1002.0",
  "groups": [],
  "tags": "frontend modules federation",
  "repo": "frontend-modules",
  "repoUrl": "https://github.com/VirtoCommerce/frontend-modules",
  "dependsOn": [],
  "optional": [],
  "incompatibleWith": []
 },
 {
  "id": "VirtoCommerce.GDPR",
  "moleculeId": "VirtoCommerce.GDPR",
  "slug": "mod-gdpr",
  "name": "GDPR",
  "registryTitle": "GDPR",
  "description": "Apply General Data Protection Regulation policies with review or remove their personal details, by anonymizing them, from your online store.",
  "version": "3.1002.0",
  "versionTag": "alpha.170",
  "platformVersion": "3.1039.0",
  "groups": [],
  "tags": "extension module",
  "repo": "vc-module-gdpr",
  "repoUrl": "https://github.com/VirtoCommerce/vc-module-gdpr",
  "dependsOn": [
   "Customer",
   "Orders"
  ],
  "optional": [],
  "incompatibleWith": []
 },
 {
  "id": "VirtoCommerce.Export",
  "moleculeId": "VirtoCommerce.Export",
  "slug": "mod-export",
  "name": "Generic Export",
  "registryTitle": "Generic Export",
  "description": "Generic export functionality",
  "version": "3.1004.0",
  "versionTag": "alpha.285",
  "platformVersion": "3.1039.0",
  "groups": [
   "commerce"
  ],
  "tags": "export",
  "repo": "vc-module-export",
  "repoUrl": "https://github.com/VirtoCommerce/vc-module-export",
  "dependsOn": [
   "Assets"
  ],
  "optional": [],
  "incompatibleWith": []
 },
 {
  "id": "VirtoCommerce.GoogleEcommerceAnalytics",
  "moleculeId": "VirtoCommerce.GoogleEcommerceAnalytics",
  "slug": "mod-google-ecommerce-analytics",
  "name": "Google Analytics 4",
  "registryTitle": "Google Analytics 4",
  "description": "Allows you active Measurement Id for a Store and measure traffic and ecommerce events to collect information about the shopping behavior of your users.",
  "version": "4.1003.0",
  "versionTag": "alpha.233",
  "platformVersion": "3.1039.0",
  "groups": [],
  "tags": "analytics",
  "repo": "vc-module-google-ecommerce-analytics",
  "repoUrl": "https://github.com/VirtoCommerce/vc-module-google-ecommerce-analytics",
  "dependsOn": [
   "Store"
  ],
  "optional": [],
  "incompatibleWith": []
 },
 {
  "id": "VirtoCommerce.GoogleSSO",
  "moleculeId": "VirtoCommerce.GoogleSSO",
  "slug": "mod-google-sso",
  "name": "Google Single Sign-On",
  "registryTitle": "Google Single Sign-On",
  "description": "Enables Google external login setup (Single Sign-On) for Virto Commerce Platform and Frontend",
  "version": "3.1003.0",
  "versionTag": "alpha.54",
  "platformVersion": "3.1039.0",
  "groups": [],
  "tags": "Google",
  "repo": "vc-module-google-sso",
  "repoUrl": "https://github.com/VirtoCommerce/vc-module-google-sso",
  "dependsOn": [],
  "optional": [],
  "incompatibleWith": []
 },
 {
  "id": "VirtoCommerce.Hotjar",
  "moleculeId": "VirtoCommerce.Hotjar",
  "slug": "mod-hotjar",
  "name": "Hotjar",
  "registryTitle": "Hotjar",
  "description": "Allows to assign Hotjar Site Id for a Store and get insights about the shopping behaviour of your users with Heatmaps, Recordings, Feedback and etc.",
  "version": "3.1002.0",
  "versionTag": "alpha.66",
  "platformVersion": "3.1007.10",
  "groups": [],
  "tags": "extension module",
  "repo": "vc-module-hotjar",
  "repoUrl": "https://github.com/VirtoCommerce/vc-module-hotjar",
  "dependsOn": [
   "Store"
  ],
  "optional": [],
  "incompatibleWith": []
 },
 {
  "id": "VirtoCommerce.ImageTools",
  "moleculeId": "VirtoCommerce.ImageTools",
  "slug": "mod-image-tools",
  "name": "Image Tools",
  "registryTitle": "Image Tools",
  "description": "Image tools helps to automate thumbnail generation procedures with resizing and cropping",
  "version": "3.1004.0",
  "versionTag": "alpha.406",
  "platformVersion": "3.1039.0",
  "groups": [
   "commerce"
  ],
  "tags": "images",
  "repo": "vc-module-image-tools",
  "repoUrl": "https://github.com/VirtoCommerce/vc-module-image-tools",
  "dependsOn": [
   "Assets"
  ],
  "optional": [],
  "incompatibleWith": []
 },
 {
  "id": "VirtoCommerce.Import",
  "moleculeId": "VirtoCommerce.Import",
  "slug": "mod-import",
  "name": "Import",
  "registryTitle": "Import module",
  "description": "Provides flexible functionality for writing Importers",
  "version": "3.1002.0",
  "versionTag": "alpha.312",
  "platformVersion": "3.1002.0",
  "groups": [],
  "tags": "extension module",
  "repo": "vc-module-Import",
  "repoUrl": "https://github.com/VirtoCommerce/vc-module-Import",
  "dependsOn": [
   "Assets",
   "Catalog",
   "Customer",
   "Notifications"
  ],
  "optional": [],
  "incompatibleWith": []
 },
 {
  "id": "VirtoCommerce.Inventory",
  "moleculeId": "VirtoCommerce.Inventory",
  "slug": "mod-inventory",
  "name": "Inventory",
  "registryTitle": "Inventory",
  "description": "Simplify inventory management functionality",
  "version": "3.1005.0",
  "versionTag": "alpha.534",
  "platformVersion": "3.1039.0",
  "groups": [
   "commerce"
  ],
  "tags": "order system",
  "repo": "vc-module-inventory",
  "repoUrl": "https://github.com/VirtoCommerce/vc-module-inventory",
  "dependsOn": [
   "Assets",
   "Catalog",
   "Core",
   "Search"
  ],
  "optional": [],
  "incompatibleWith": []
 },
 {
  "id": "VirtoCommerce.Loyalty",
  "moleculeId": "VirtoCommerce.Loyalty",
  "slug": "mod-loyalty",
  "name": "Loyalty",
  "registryTitle": "Loyalty",
  "description": "Customer loyalty program is offering your customers some reward for shopping at your store.",
  "version": "3.1005.0",
  "versionTag": "alpha.41",
  "platformVersion": "3.1039.0",
  "groups": [],
  "tags": "extension module",
  "repo": "vc-module-loyalty",
  "repoUrl": "https://github.com/VirtoCommerce/vc-module-loyalty",
  "dependsOn": [
   "Catalog",
   "Core",
   "Orders",
   "XCart",
   "XCatalog"
  ],
  "optional": [],
  "incompatibleWith": []
 },
 {
  "id": "VirtoCommerce.LuceneSearch",
  "moleculeId": "VirtoCommerce.LuceneSearch",
  "slug": "mod-lucene-search",
  "name": "Lucene Search",
  "registryTitle": "Lucene Search",
  "description": "Indexed search functionality with Lucene engine",
  "version": "3.1005.0",
  "versionTag": "alpha.252",
  "platformVersion": "3.1039.0",
  "groups": [
   "commerce"
  ],
  "tags": "lucene search",
  "repo": "vc-module-lucene-search",
  "repoUrl": "https://github.com/VirtoCommerce/vc-module-lucene-search",
  "dependsOn": [
   "Search"
  ],
  "optional": [],
  "incompatibleWith": []
 },
 {
  "id": "VirtoCommerce.Marketing",
  "moleculeId": "VirtoCommerce.Marketing",
  "slug": "mod-marketing",
  "name": "Marketing",
  "registryTitle": "Marketing",
  "description": "Marketing system with dynamic contents and promotions management",
  "version": "3.1007.0",
  "versionTag": "alpha.937",
  "platformVersion": "3.1039.0",
  "groups": [
   "commerce"
  ],
  "tags": "marketing promotion",
  "repo": "vc-module-marketing",
  "repoUrl": "https://github.com/VirtoCommerce/vc-module-marketing",
  "dependsOn": [
   "Assets",
   "Catalog",
   "Core",
   "Payment",
   "Shipping",
   "Store"
  ],
  "optional": [
   "Customer",
   "Orders"
  ],
  "incompatibleWith": []
 },
 {
  "id": "VirtoCommerce.MarketingExperienceApi",
  "moleculeId": "VirtoCommerce.MarketingExperienceApi",
  "slug": "mod-marketing-experience-api",
  "name": "Marketing Experience API",
  "registryTitle": "Marketing Experience API",
  "description": "Experience Api extension for Marketing",
  "version": "3.1004.0",
  "versionTag": "alpha.103",
  "platformVersion": "3.1002.0",
  "groups": [],
  "tags": "extension module",
  "repo": "vc-module-marketing-experience-api",
  "repoUrl": "https://github.com/VirtoCommerce/vc-module-marketing-experience-api",
  "dependsOn": [
   "Customer",
   "Marketing",
   "Xapi"
  ],
  "optional": [],
  "incompatibleWith": []
 },
 {
  "id": "VirtoCommerce.NativePaymentMethods",
  "moleculeId": "VirtoCommerce.NativePaymentMethods",
  "slug": "mod-native-payment-methods",
  "name": "Native Payment Methods",
  "registryTitle": "Native Payment Methods",
  "description": "Non-integrative payment methods support",
  "version": "3.1003.0",
  "versionTag": "alpha.123",
  "platformVersion": "3.1017.0",
  "groups": [],
  "tags": "extension module",
  "repo": "vc-module-NativePaymentMethods",
  "repoUrl": "https://github.com/VirtoCommerce/vc-module-NativePaymentMethods",
  "dependsOn": [
   "Payment"
  ],
  "optional": [],
  "incompatibleWith": []
 },
 {
  "id": "VirtoCommerce.News",
  "moleculeId": "VirtoCommerce.News",
  "slug": "mod-news",
  "name": "News",
  "registryTitle": "News",
  "description": "Module allowing content managers to publish news articles",
  "version": "3.1005.0",
  "versionTag": "alpha.73",
  "platformVersion": "3.1039.0",
  "groups": [],
  "tags": "extension module",
  "repo": "vc-module-news",
  "repoUrl": "https://github.com/VirtoCommerce/vc-module-news",
  "dependsOn": [
   "Xapi"
  ],
  "optional": [],
  "incompatibleWith": []
 },
 {
  "id": "VirtoCommerce.Notifications",
  "moleculeId": "VirtoCommerce.Notifications",
  "slug": "mod-notifications",
  "name": "Notifications",
  "registryTitle": "Notifications",
  "description": "Provides a comprehensive infrastructure for managing and delivering notifications within the Virto Commerce platform.",
  "version": "3.1013.0",
  "versionTag": "alpha.488",
  "platformVersion": "3.1039.0",
  "groups": [
   "commerce"
  ],
  "tags": "notifications",
  "repo": "vc-module-notification",
  "repoUrl": "https://github.com/VirtoCommerce/vc-module-notification",
  "dependsOn": [
   "Assets"
  ],
  "optional": [],
  "incompatibleWith": []
 },
 {
  "id": "VirtoCommerce.OpenSearch",
  "moleculeId": "VirtoCommerce.OpenSearch",
  "slug": "mod-open-search",
  "name": "Open Search",
  "registryTitle": "Open Search",
  "description": "Indexed search functionality with OpenSearch",
  "version": "3.1002.0",
  "versionTag": "alpha.32",
  "platformVersion": "3.1002.0",
  "groups": [],
  "tags": "extension module",
  "repo": "vc-module-open-search",
  "repoUrl": "https://github.com/VirtoCommerce/vc-module-open-search",
  "dependsOn": [
   "Search"
  ],
  "optional": [],
  "incompatibleWith": []
 },
 {
  "id": "VirtoCommerce.OpenTelemetry",
  "moleculeId": "VirtoCommerce.OpenTelemetry",
  "slug": "mod-open-telemetry",
  "name": "Open Telemetry",
  "registryTitle": "Open Telemetry",
  "description": "Provides Open Telemetry metrics, tracing, and logging via OTLP exporter",
  "version": "3.1001.0",
  "versionTag": "alpha.4",
  "platformVersion": "3.1002.0",
  "groups": [],
  "tags": "extension module",
  "repo": "vc-module-opentelemetry",
  "repoUrl": "https://github.com/VirtoCommerce/vc-module-opentelemetry",
  "dependsOn": [],
  "optional": [],
  "incompatibleWith": []
 },
 {
  "id": "VirtoCommerce.OpenIdConnectModule",
  "moleculeId": "VirtoCommerce.OpenIdConnectModule",
  "slug": "mod-open-id-connect",
  "name": "OpenID Connect",
  "registryTitle": "OpenID Connect",
  "description": "OpenID Connect is an identity module on top of the OAuth 2.0",
  "version": "3.1002.0",
  "versionTag": "alpha.45",
  "platformVersion": "3.1002.0",
  "groups": [],
  "tags": "extension module",
  "repo": "vc-module-openid-connect",
  "repoUrl": "https://github.com/VirtoCommerce/vc-module-openid-connect",
  "dependsOn": [],
  "optional": [],
  "incompatibleWith": []
 },
 {
  "id": "VirtoCommerce.XOrder",
  "moleculeId": "VirtoCommerce.XOrder",
  "slug": "mod-xorder",
  "name": "Order Experience API",
  "registryTitle": "Order Experience API",
  "description": "Focuses on order processing, providing robust support for order lifecycle management.",
  "version": "3.1009.0",
  "versionTag": "alpha.126",
  "platformVersion": "3.1039.0",
  "groups": [
   "commerce"
  ],
  "tags": "extension module",
  "repo": "vc-module-x-order",
  "repoUrl": "https://github.com/VirtoCommerce/vc-module-x-order",
  "dependsOn": [
   "FileExperienceApi",
   "Orders",
   "Payment",
   "XCart",
   "XCatalog",
   "Xapi"
  ],
  "optional": [],
  "incompatibleWith": []
 },
 {
  "id": "VirtoCommerce.Orders",
  "moleculeId": "VirtoCommerce.Orders",
  "slug": "mod-orders",
  "name": "Order Management",
  "registryTitle": "Order Management",
  "description": "Document based flexible order management system.",
  "version": "3.1013.0",
  "versionTag": "alpha.1437",
  "platformVersion": "3.1039.0",
  "groups": [
   "commerce"
  ],
  "tags": "order system",
  "repo": "vc-module-order",
  "repoUrl": "https://github.com/VirtoCommerce/vc-module-order",
  "dependsOn": [
   "Assets",
   "Cart",
   "Catalog",
   "Core",
   "Customer",
   "Inventory",
   "Notifications",
   "Payment",
   "Search",
   "Shipping",
   "Store"
  ],
  "optional": [],
  "incompatibleWith": []
 },
 {
  "id": "VirtoCommerce.OrderManagement",
  "moleculeId": "VirtoCommerce.OrderManagement",
  "slug": "mod-order-management",
  "name": "Order Management (Business Rules)",
  "registryTitle": "Order Management (Business Rules)",
  "description": "Consolidates order management business rules.",
  "version": "3.1003.0",
  "versionTag": "alpha.43",
  "platformVersion": "3.1002.0",
  "groups": [],
  "tags": "extension module",
  "repo": "vc-module-order-management",
  "repoUrl": "https://github.com/VirtoCommerce/vc-module-order-management",
  "dependsOn": [
   "Catalog",
   "Orders",
   "Store"
  ],
  "optional": [
   "XCatalog"
  ],
  "incompatibleWith": []
 },
 {
  "id": "VirtoCommerce.Payment",
  "moleculeId": "VirtoCommerce.Payment",
  "slug": "mod-payment",
  "name": "Payment",
  "registryTitle": "Payment module",
  "description": "Provides management and integration of various payment methods.",
  "version": "3.1006.0",
  "versionTag": "alpha.294",
  "platformVersion": "3.1039.0",
  "groups": [
   "commerce"
  ],
  "tags": "payments",
  "repo": "vc-module-payment",
  "repoUrl": "https://github.com/VirtoCommerce/vc-module-payment",
  "dependsOn": [
   "Core",
   "Store"
  ],
  "optional": [],
  "incompatibleWith": []
 },
 {
  "id": "VirtoCommerce.PriceExportImport",
  "moleculeId": "VirtoCommerce.PriceExportImport",
  "slug": "mod-price-export-import",
  "name": "Price Export Import",
  "registryTitle": "Price Export Import",
  "description": "This module adds prices export and import functionality using it for price management.",
  "version": "3.1002.0",
  "versionTag": "alpha.188",
  "platformVersion": "3.1002.0",
  "groups": [],
  "tags": "price import export",
  "repo": "vc-module-price-export-import",
  "repoUrl": "https://github.com/VirtoCommerce/vc-module-price-export-import",
  "dependsOn": [
   "Assets",
   "Catalog",
   "Export",
   "Pricing"
  ],
  "optional": [],
  "incompatibleWith": []
 },
 {
  "id": "VirtoCommerce.Pricing",
  "moleculeId": "VirtoCommerce.Pricing",
  "slug": "mod-pricing",
  "name": "Pricing",
  "registryTitle": "Pricing",
  "description": "Robust pricing management functionality based on price list and dynamic evaluation",
  "version": "3.1005.0",
  "versionTag": "alpha.814",
  "platformVersion": "3.1039.0",
  "groups": [
   "commerce"
  ],
  "tags": "price pricelist merchandise",
  "repo": "vc-module-pricing",
  "repoUrl": "https://github.com/VirtoCommerce/vc-module-pricing",
  "dependsOn": [
   "Assets",
   "Catalog",
   "Core",
   "Search"
  ],
  "optional": [
   "Export"
  ],
  "incompatibleWith": []
 },
 {
  "id": "VirtoCommerce.XRecommend",
  "moleculeId": "VirtoCommerce.XRecommend",
  "slug": "mod-xrecommend",
  "name": "Product Recommendations",
  "registryTitle": "Product Recommendations",
  "description": "Recommendations encourage users to expand their search and browse more broadly. Users can jump to similar or complementary items if they don’t find a precise match.",
  "version": "3.1002.0",
  "versionTag": "alpha.66",
  "platformVersion": "3.1007.10",
  "groups": [],
  "tags": "extension module",
  "repo": "vc-module-x-recommend",
  "repoUrl": "https://github.com/VirtoCommerce/vc-module-x-recommend",
  "dependsOn": [
   "XCatalog",
   "Xapi"
  ],
  "optional": [],
  "incompatibleWith": []
 },
 {
  "id": "VirtoCommerce.ProductSnapshot",
  "moleculeId": "VirtoCommerce.ProductSnapshot",
  "slug": "mod-product-snapshot",
  "name": "Product Snapshot",
  "registryTitle": "Product Snapshot",
  "description": "The Product Snapshot module captures and stores product information at the moment an order is created.\n  This ensures that customers and store operators always have access to the exact product details (prices, properties, images, descriptions)\n  that were valid at the time of purchase, even if the product catalog is later modified or products are deleted.",
  "version": "3.1003.0",
  "versionTag": "alpha.23",
  "platformVersion": "3.1016.0",
  "groups": [],
  "tags": "extension module",
  "repo": "vc-module-product-snapshot",
  "repoUrl": "https://github.com/VirtoCommerce/vc-module-product-snapshot",
  "dependsOn": [
   "Catalog",
   "Orders",
   "XOrder"
  ],
  "optional": [],
  "incompatibleWith": []
 },
 {
  "id": "VirtoCommerce.PushMessages",
  "moleculeId": "VirtoCommerce.PushMessages",
  "slug": "mod-push-messages",
  "name": "Push Messages",
  "registryTitle": "Push Messages",
  "description": "Enables back-end admins to send custom notifications to selected organizations within the Virto Commerce platform.",
  "version": "3.1005.0",
  "versionTag": "alpha.112",
  "platformVersion": "3.1039.0",
  "groups": [],
  "tags": "extension module",
  "repo": "vc-module-push-messages",
  "repoUrl": "https://github.com/VirtoCommerce/vc-module-push-messages",
  "dependsOn": [
   "Customer",
   "Xapi"
  ],
  "optional": [],
  "incompatibleWith": []
 },
 {
  "id": "VirtoCommerce.Quote",
  "moleculeId": "VirtoCommerce.Quote",
  "slug": "mod-quote",
  "name": "Quotes",
  "registryTitle": "Quotes",
  "description": "Quoter enables business users to execute quote requests online. Once initiated, an online conversation takes place with internal users who interact with the business user's request. The internal user can set prices for quantity breaks or discounts. The quote is then made available to the business user online. The business user can accept the quote and place the order, continue the conversation, or reject the quote.",
  "version": "3.1002.0",
  "versionTag": "alpha.508",
  "platformVersion": "3.1039.0",
  "groups": [],
  "tags": "b2b quotes",
  "repo": "vc-module-quote",
  "repoUrl": "https://github.com/VirtoCommerce/vc-module-quote",
  "dependsOn": [
   "Assets",
   "Cart",
   "Catalog",
   "Core",
   "Customer",
   "FileExperienceApi",
   "Orders",
   "Shipping",
   "Store",
   "Tax",
   "XCart",
   "XCatalog",
   "Xapi"
  ],
  "optional": [],
  "incompatibleWith": []
 },
 {
  "id": "VirtoCommerce.CustomerReviews",
  "moleculeId": "VirtoCommerce.CustomerReviews",
  "slug": "mod-customer-reviews",
  "name": "Rating and Reviews",
  "registryTitle": "Rating and Reviews",
  "description": "Enables customers to share their feedback on products and vendors after making a purchase, helping others make informed decisions.",
  "version": "3.1006.0",
  "versionTag": "alpha.291",
  "platformVersion": "3.1039.0",
  "groups": [],
  "tags": "customer review",
  "repo": "vc-module-customer-review",
  "repoUrl": "https://github.com/VirtoCommerce/vc-module-customer-review",
  "dependsOn": [
   "Assets",
   "Catalog",
   "Customer",
   "FileExperienceApi",
   "Notifications",
   "Orders",
   "ProfileExperienceApiModule",
   "Store",
   "XCatalog",
   "Xapi"
  ],
  "optional": [],
  "incompatibleWith": []
 },
 {
  "id": "VirtoCommerce.Return",
  "moleculeId": "VirtoCommerce.Return",
  "slug": "mod-return",
  "name": "Returns",
  "registryTitle": "Returns",
  "description": "Return management module",
  "version": "3.1002.0",
  "versionTag": "alpha.149",
  "platformVersion": "3.1039.0",
  "groups": [],
  "tags": "extension module",
  "repo": "vc-module-return",
  "repoUrl": "https://github.com/VirtoCommerce/vc-module-return",
  "dependsOn": [
   "Orders",
   "Store"
  ],
  "optional": [],
  "incompatibleWith": []
 },
 {
  "id": "VirtoCommerce.SalesRep",
  "moleculeId": "VirtoCommerce.SalesRep",
  "slug": "mod-sales-rep",
  "name": "Sales Rep",
  "registryTitle": "Virto Commerce Sales Rep",
  "description": "Virto Commerce Sales Rep",
  "version": "3.1003.0",
  "versionTag": "alpha.17",
  "platformVersion": "3.1048.0",
  "groups": [],
  "tags": "extension module",
  "repo": "vc-module-sales-rep",
  "repoUrl": "https://github.com/VirtoCommerce/vc-module-sales-rep",
  "dependsOn": [
   "Cart",
   "Catalog",
   "Core",
   "Customer",
   "Notifications",
   "Orders",
   "PushMessages",
   "Store",
   "XCart",
   "Xapi"
  ],
  "optional": [],
  "incompatibleWith": []
 },
 {
  "id": "VirtoCommerce.Sanity",
  "moleculeId": "VirtoCommerce.Sanity",
  "slug": "mod-sanity",
  "name": "Sanity",
  "registryTitle": "Sanity",
  "description": "Integration module for Sanity CMS",
  "version": "3.1004.0",
  "versionTag": "alpha.11",
  "platformVersion": "3.1002.0",
  "groups": [],
  "tags": "extension module",
  "repo": "vc-module-sanity",
  "repoUrl": "https://github.com/VirtoCommerce/vc-module-sanity",
  "dependsOn": [
   "Store"
  ],
  "optional": [
   "Pages"
  ],
  "incompatibleWith": []
 },
 {
  "id": "VirtoCommerce.Search",
  "moleculeId": "VirtoCommerce.Search",
  "slug": "mod-search",
  "name": "Search Core",
  "registryTitle": "Search Core",
  "description": "Defines Core Abstractions for indexed search functionality above different search providers, like: Elasticsearch, Azure Search, etc.",
  "version": "3.1007.0",
  "versionTag": "pr-144-37cd",
  "platformVersion": "3.1039.0",
  "groups": [
   "commerce"
  ],
  "tags": "security core",
  "repo": "vc-module-search",
  "repoUrl": "https://github.com/VirtoCommerce/vc-module-search",
  "dependsOn": [],
  "optional": [],
  "incompatibleWith": []
 },
 {
  "id": "VirtoCommerce.Seo",
  "moleculeId": "VirtoCommerce.Seo",
  "slug": "mod-seo",
  "name": "SEO",
  "registryTitle": "SEO",
  "description": "Infrastructure for managing SEO metadata across the platform",
  "version": "3.1005.0",
  "versionTag": "alpha.89",
  "platformVersion": "3.1039.0",
  "groups": [
   "commerce"
  ],
  "tags": "extension module",
  "repo": "vc-module-seo",
  "repoUrl": "https://github.com/VirtoCommerce/vc-module-seo",
  "dependsOn": [],
  "optional": [],
  "incompatibleWith": []
 },
 {
  "id": "VirtoCommerce.SeqLog",
  "moleculeId": "VirtoCommerce.SeqLog",
  "slug": "mod-seq-log",
  "name": "Seq log sink",
  "registryTitle": "SeqLog",
  "description": "Writes logs events to Serilog Seq",
  "version": "3.1002.0",
  "versionTag": "alpha.45",
  "platformVersion": "3.1002.0",
  "groups": [],
  "tags": "extension module",
  "repo": "vc-module-seq-log",
  "repoUrl": "https://github.com/VirtoCommerce/vc-module-seq-log",
  "dependsOn": [],
  "optional": [],
  "incompatibleWith": []
 },
 {
  "id": "VirtoCommerce.Shipping",
  "moleculeId": "VirtoCommerce.Shipping",
  "slug": "mod-shipping",
  "name": "Shipping",
  "registryTitle": "Shipping",
  "description": "Add shipping methods management",
  "version": "3.1007.0",
  "versionTag": "alpha.267",
  "platformVersion": "3.1039.0",
  "groups": [
   "commerce"
  ],
  "tags": "shipping",
  "repo": "vc-module-shipping",
  "repoUrl": "https://github.com/VirtoCommerce/vc-module-shipping",
  "dependsOn": [
   "Core",
   "Search",
   "Store"
  ],
  "optional": [],
  "incompatibleWith": []
 },
 {
  "id": "VirtoCommerce.ShipStation",
  "moleculeId": "VirtoCommerce.ShipStation",
  "slug": "mod-ship-station",
  "name": "ShipStation Integration",
  "registryTitle": "ShipStation Integration",
  "description": "Enables synchronizing customer orders with ShipStation",
  "version": "3.1002.0",
  "versionTag": "alpha.152",
  "platformVersion": "3.1002.0",
  "groups": [],
  "tags": "extension module",
  "repo": "vc-module-ShipStation",
  "repoUrl": "https://github.com/VirtoCommerce/vc-module-ShipStation",
  "dependsOn": [
   "Orders"
  ],
  "optional": [],
  "incompatibleWith": []
 },
 {
  "id": "VirtoCommerce.Cart",
  "moleculeId": "VirtoCommerce.Cart",
  "slug": "mod-cart",
  "name": "Shopping Cart",
  "registryTitle": "Shopping Cart",
  "description": "Shopping cart / checkout functionality",
  "version": "3.1009.0",
  "versionTag": "alpha.805",
  "platformVersion": "3.1039.0",
  "groups": [
   "commerce"
  ],
  "tags": "shopping cart",
  "repo": "vc-module-cart",
  "repoUrl": "https://github.com/VirtoCommerce/vc-module-cart",
  "dependsOn": [
   "Assets",
   "Core",
   "Customer",
   "Notifications",
   "Payment",
   "Shipping",
   "Store"
  ],
  "optional": [
   "Search"
  ],
  "incompatibleWith": []
 },
 {
  "id": "VirtoCommerce.Sitemaps",
  "moleculeId": "VirtoCommerce.Sitemaps",
  "slug": "mod-sitemaps",
  "name": "Sitemap Generator",
  "registryTitle": "Sitemap Generator",
  "description": "Simplifies the process of generating sitemaps for online stores",
  "version": "3.1004.0",
  "versionTag": "alpha.421",
  "platformVersion": "3.1039.0",
  "groups": [
   "commerce"
  ],
  "tags": "sitemaps",
  "repo": "vc-module-sitemaps",
  "repoUrl": "https://github.com/VirtoCommerce/vc-module-sitemaps",
  "dependsOn": [
   "Assets",
   "Catalog",
   "Content",
   "Core",
   "Customer",
   "Store"
  ],
  "optional": [],
  "incompatibleWith": []
 },
 {
  "id": "VirtoCommerce.Skyflow",
  "moleculeId": "VirtoCommerce.Skyflow",
  "slug": "mod-skyflow",
  "name": "Skyflow",
  "registryTitle": "Skyflow",
  "description": "Skyflow Integration as payment provider enables a unified user experience for Credit Card transactions across diverse payment providers.",
  "version": "3.1004.0",
  "versionTag": "alpha.81",
  "platformVersion": "3.1002.0",
  "groups": [],
  "tags": "extension module",
  "repo": "vc-module-skyflow",
  "repoUrl": "https://github.com/VirtoCommerce/vc-module-skyflow",
  "dependsOn": [
   "Orders",
   "Payment",
   "Xapi"
  ],
  "optional": [],
  "incompatibleWith": []
 },
 {
  "id": "VirtoCommerce.SqlQueries",
  "moleculeId": "VirtoCommerce.SqlQueries",
  "slug": "mod-sql-queries",
  "name": "Sql Queries",
  "registryTitle": "Sql Queries",
  "description": "Adds SQL query/report capabilities to the VirtoCommerce platform, enabling advanced data access directly through SQL.",
  "version": "3.1006.0",
  "versionTag": "alpha.52",
  "platformVersion": "3.1007.10",
  "groups": [],
  "tags": "extension module",
  "repo": "vc-module-sql-queries",
  "repoUrl": "https://github.com/VirtoCommerce/vc-module-sql-queries",
  "dependsOn": [],
  "optional": [],
  "incompatibleWith": []
 },
 {
  "id": "VirtoCommerce.StateMachine",
  "moleculeId": "VirtoCommerce.StateMachine",
  "slug": "mod-state-machine",
  "name": "State Machine",
  "registryTitle": "StateMachine module",
  "description": "Provides core functionality for entity's State Machine",
  "version": "3.1003.0",
  "versionTag": "alpha.145",
  "platformVersion": "3.1007.10",
  "groups": [],
  "tags": "VirtoCommerce State Machine module",
  "repo": "vc-module-state-machine",
  "repoUrl": "https://github.com/VirtoCommerce/vc-module-state-machine",
  "dependsOn": [
   "Core"
  ],
  "optional": [],
  "incompatibleWith": []
 },
 {
  "id": "VirtoCommerce.Store",
  "moleculeId": "VirtoCommerce.Store",
  "slug": "mod-store",
  "name": "Store",
  "registryTitle": "Store",
  "description": "Multi store management with individual store settings",
  "version": "3.1006.0",
  "versionTag": "alpha.787",
  "platformVersion": "3.1039.0",
  "groups": [
   "commerce"
  ],
  "tags": "stores",
  "repo": "vc-module-store",
  "repoUrl": "https://github.com/VirtoCommerce/vc-module-store",
  "dependsOn": [
   "Core",
   "Notifications",
   "Seo"
  ],
  "optional": [],
  "incompatibleWith": []
 },
 {
  "id": "VirtoCommerce.Subscription",
  "moleculeId": "VirtoCommerce.Subscription",
  "slug": "mod-subscription",
  "name": "Subscriptions",
  "registryTitle": "Subscriptions",
  "description": "Represent recurrent subscriptions functionality",
  "version": "3.1003.0",
  "versionTag": "alpha.387",
  "platformVersion": "3.1039.0",
  "groups": [
   "commerce"
  ],
  "tags": "subscriptions system",
  "repo": "vc-module-subscription",
  "repoUrl": "https://github.com/VirtoCommerce/vc-module-subscription",
  "dependsOn": [
   "Core",
   "Customer",
   "Notifications",
   "Orders",
   "Store"
  ],
  "optional": [],
  "incompatibleWith": []
 },
 {
  "id": "VirtoCommerce.SystemOperations",
  "moleculeId": "VirtoCommerce.SystemOperations",
  "slug": "mod-system-operations",
  "name": "System Operations",
  "registryTitle": "System Operations",
  "description": "Developer tools page with centralized platform maintenance operations.",
  "version": "3.1002.0",
  "versionTag": "alpha.21",
  "platformVersion": "3.1007.22",
  "groups": [],
  "tags": "developer-tools system operations maintenance",
  "repo": "vc-module-system-operations",
  "repoUrl": "https://github.com/VirtoCommerce/vc-module-system-operations",
  "dependsOn": [],
  "optional": [],
  "incompatibleWith": []
 },
 {
  "id": "VirtoCommerce.TaskManagement",
  "moleculeId": "VirtoCommerce.TaskManagement",
  "slug": "mod-task-management",
  "name": "Task Management",
  "registryTitle": "Task Management",
  "description": "Headquarters personas can use task management to create task lists for retail stores, and to track status by store or worker.",
  "version": "3.1005.0",
  "versionTag": "alpha.208",
  "platformVersion": "3.1025.0",
  "groups": [],
  "tags": "",
  "repo": "vc-module-task-management",
  "repoUrl": "https://github.com/VirtoCommerce/vc-module-task-management",
  "dependsOn": [
   "Customer",
   "Notifications",
   "Xapi"
  ],
  "optional": [],
  "incompatibleWith": []
 },
 {
  "id": "VirtoCommerce.Tax",
  "moleculeId": "VirtoCommerce.Tax",
  "slug": "mod-tax",
  "name": "Tax Core",
  "registryTitle": "Tax Core",
  "description": "Defines Core Abstractions for taxes evaluation by using different tax providers and FixedRateTaxProvider.",
  "version": "3.1005.0",
  "versionTag": "alpha.238",
  "platformVersion": "3.1039.0",
  "groups": [
   "commerce"
  ],
  "tags": "stores",
  "repo": "vc-module-tax",
  "repoUrl": "https://github.com/VirtoCommerce/vc-module-tax",
  "dependsOn": [
   "Core",
   "Store"
  ],
  "optional": [],
  "incompatibleWith": []
 },
 {
  "id": "VirtoCommerce.UCP",
  "moleculeId": "VirtoCommerce.UCP",
  "slug": "mod-ucp",
  "name": "Universal Commerce Protocol",
  "registryTitle": "Universal Commerce Protocol",
  "description": "Universal Commerce Protocol facade for Virto Commerce capabilities.",
  "version": "3.1004.0",
  "versionTag": "alpha.14",
  "platformVersion": "3.1034.0",
  "groups": [],
  "tags": "ucp commerce mcp checkout catalog cart",
  "repo": "vc-module-u-c-p",
  "repoUrl": "https://github.com/VirtoCommerce/vc-module-u-c-p",
  "dependsOn": [
   "Marketing",
   "Orders",
   "Store",
   "XCart",
   "XCatalog",
   "Xapi"
  ],
  "optional": [],
  "incompatibleWith": []
 },
 {
  "id": "VirtoCommerce.Pages",
  "moleculeId": "VirtoCommerce.Pages",
  "slug": "mod-pages",
  "name": "Virto Pages",
  "registryTitle": "Virto Pages",
  "description": "Provides a robust and flexible solution for managing content in digital commerce scenarios. Decoupling the CMS post-publishing ensures long-term efficiency, adaptability, and performance.",
  "version": "3.1008.0",
  "versionTag": "alpha.75",
  "platformVersion": "3.1039.0",
  "groups": [],
  "tags": "extension module",
  "repo": "vc-module-pages",
  "repoUrl": "https://github.com/VirtoCommerce/vc-module-pages",
  "dependsOn": [
   "Customer",
   "Search",
   "Seo",
   "Store"
  ],
  "optional": [],
  "incompatibleWith": []
 },
 {
  "id": "VirtoCommerce.WebHooks",
  "moleculeId": "VirtoCommerce.WebHooks",
  "slug": "mod-web-hooks",
  "name": "Webhooks",
  "registryTitle": "Webhooks",
  "description": "Manage user defined webhooks",
  "version": "3.1005.0",
  "versionTag": "alpha.354",
  "platformVersion": "3.1039.0",
  "groups": [],
  "tags": "webhooks module",
  "repo": "vc-module-webhooks",
  "repoUrl": "https://github.com/VirtoCommerce/vc-module-webhooks",
  "dependsOn": [],
  "optional": [],
  "incompatibleWith": []
 },
 {
  "id": "VirtoCommerce.WhiteLabeling",
  "moleculeId": "VirtoCommerce.WhiteLabeling",
  "slug": "mod-white-labeling",
  "name": "White Labeling",
  "registryTitle": "White Labeling",
  "description": "Provides White labeling functionality for organizations",
  "version": "3.1004.0",
  "versionTag": "alpha.91",
  "platformVersion": "3.1039.0",
  "groups": [],
  "tags": "extension module",
  "repo": "vc-module-white-labeling",
  "repoUrl": "https://github.com/VirtoCommerce/vc-module-white-labeling",
  "dependsOn": [
   "Customer",
   "FileExperienceApi",
   "ImageTools",
   "XCMS",
   "Xapi"
  ],
  "optional": [],
  "incompatibleWith": []
 }
];
