#!/usr/bin/env node
/* content/modules/*.json  →  content/modules.generated.js
 *
 * The map loads with plain <script src> tags on file://, so it cannot read a directory. One
 * generated file keeps index.html unchanged as the catalog grows, while the authored unit stays one
 * JSON per module — reviewable, diffable, and writable by the profiler without merge conflicts.
 *
 * Usage: node tools/build-modules.js [--check]
 */
const fs = require('fs');
const path = require('path');

const ROOT = path.resolve(__dirname, '..');
const SRC = path.join(ROOT, 'content/modules');
const OUT = path.join(ROOT, 'content/modules.generated.js');
const CHECK = process.argv.includes('--check');

const files = fs.existsSync(SRC) ? fs.readdirSync(SRC).filter(f => f.endsWith('.json')).sort() : [];
const profiles = files.map(f => JSON.parse(fs.readFileSync(path.join(SRC, f), 'utf8')));

/* Sorted by name so the catalog order is stable regardless of when a module was profiled. */
profiles.sort((a, b) => String(a.name).localeCompare(String(b.name)));

const authored = profiles.filter(p => p.notes && p.notes.forAnalyst).length;
const body = [
  '/* GENERATED by tools/build-modules.js from content/modules/*.json — do not edit by hand.',
  ' * ' + profiles.length + ' module profile(s), ' + authored + ' with authored notes.',
  ' * Add or refresh one with: node tools/module-profile.js vc-module-<name>',
  ' */',
  'window.VC_MODULE_PROFILES = ' + JSON.stringify(profiles, null, 1) + ';',
  ''
].join('\n');

if (CHECK) {
  const current = fs.existsSync(OUT) ? fs.readFileSync(OUT, 'utf8') : '';
  if (current !== body) { console.error('modules.generated.js is STALE — run node tools/build-modules.js'); process.exit(1); }
  console.log('modules.generated.js is up to date (' + profiles.length + ' profiles)');
} else {
  fs.writeFileSync(OUT, body);
  console.log('wrote content/modules.generated.js — ' + profiles.length + ' profile(s), ' + authored + ' with notes');
  for (const p of profiles) {
    console.log('  ' + String(p.id).padEnd(30) + String(p.latestVersion).padEnd(11) +
                (p.notes && p.notes.forAnalyst ? 'notes' : 'facts only'));
  }
}
