#!/usr/bin/env node
/* content/modules/*.json  →  content/modules.generated.js
 *
 * The map loads with plain <script src> tags on file://, so it cannot read a directory. One
 * generated file keeps index.html unchanged as the catalog grows, while the authored unit stays one
 * JSON per module — reviewable, diffable, and writable by the profiler without merge conflicts.
 *
 * Usage: node tools/build-modules.js [--check]
 */
const fs = require('fs');
const path = require('path');

const ROOT = path.resolve(__dirname, '..');
const SRC = path.join(ROOT, 'content/modules');
const OUT = path.join(ROOT, 'content/modules.generated.js');
const CHECK = process.argv.includes('--check');

const files = fs.existsSync(SRC) ? fs.readdirSync(SRC).filter(f => f.endsWith('.json')).sort() : [];
const raw = files.map(f => JSON.parse(fs.readFileSync(path.join(SRC, f), 'utf8')));

/* Ship what a page draws. The profile on disk keeps every path it found — useful when auditing a
   claim — but the browser only needs counts for those, and shipping the paths added ~30% to a file
   that loads on every visit. */
const profiles = raw.map(p => {
  const f = p.facts || {};
  return Object.assign({}, p, {
    facts: Object.assign({}, f, {
      eventHandlers: undefined,
      eventHandlerCount: (f.eventHandlers || []).length || undefined,
      graphqlBuilders: undefined,
      graphqlBuilderCount: (f.graphqlBuilders || []).length || undefined,
      indexDocumentBuilders: undefined,
      indexDocumentBuilderCount: (f.indexDocumentBuilders || []).length || undefined,
      restControllers: (f.restControllers || []).map(c => ({ route: c.route, actions: c.actions, authorizedActions: c.authorizedActions }))
    })
  });
});

/* Sorted by name so the catalog order is stable regardless of when a module was profiled. */
profiles.sort((a, b) => String(a.name).localeCompare(String(b.name)));

const authored = profiles.filter(p => p.notes && p.notes.forAnalyst).length;
const bytesOnDisk = raw.reduce((n, p) => n + JSON.stringify(p).length, 0);
const body = [
  '/* GENERATED by tools/build-modules.js from content/modules/*.json — do not edit by hand.',
  ' * ' + profiles.length + ' module profile(s), ' + authored + ' with authored notes.',
  ' * Add or refresh one with: node tools/module-profile.js vc-module-<name>',
  ' */',
  /* No indentation: 96 profiles pretty-printed cost more than the file paths this projection strips.
     Nobody reads a generated file by hand — the per-module JSON is what a human edits. */
  'window.VC_MODULE_PROFILES = ' + JSON.stringify(profiles) + ';',
  ''
].join('\n');

if (CHECK) {
  const current = fs.existsSync(OUT) ? fs.readFileSync(OUT, 'utf8') : '';
  if (current !== body) { console.error('modules.generated.js is STALE — run node tools/build-modules.js'); process.exit(1); }
  console.log('modules.generated.js is up to date (' + profiles.length + ' profiles)');
} else {
  fs.writeFileSync(OUT, body);
  console.log('wrote content/modules.generated.js — ' + profiles.length + ' profile(s), ' + authored + ' with notes; ' +
              Math.round(body.length / 1024) + 'KB shipped of ' + Math.round(bytesOnDisk / 1024) + 'KB on disk');
  const written = profiles.filter(p => p.notes && p.notes.forAnalyst).map(p => p.id.replace('VirtoCommerce.', ''));
  console.log('  written up: ' + (written.join(', ') || 'none yet'));
  const noReadme = profiles.filter(p => !p.readme || !p.readme.overview).map(p => p.id.replace('VirtoCommerce.', ''));
  if (noReadme.length) console.log('  no README overview (' + noReadme.length + '): ' + noReadme.join(', '));
}
